version: "3"
services:
  bot-server:
    build: .docker/bot-server
    #restart: always
    working_dir: /teto/build/
    depends_on:
      - redis
      - bot-typescript
    volumes:
      - ./build:/teto/build
      - ./node_modules:/teto/build/node_modules
      - ./databases:/teto/databases
      - ./schemas:/teto/schemas
    networks:
      - backend
    environment:
      - BOT_ID=$BOT_ID
      - BOT_TOKEN=$BOT_TOKEN
      - BOT_PREFIX=$BOT_PREFIX
      - REDIS_URL=redis://127.0.0.1:6379
    command: node teto.js
  bot-typescript:
    build: .docker/bot-typescript
    working_dir: /teto
    volumes: 
      - ./src:/teto/src
      - ./:/teto
      - ./node_modules:/teto/node_modules
    command: bash -c "yarn install && npx tsc --preserveWatchOutput --pretty --watch"
  redis:
    build: .docker/redis
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  backend: {}
