version: "3"
services:
  bot:
    image: node:15-alpine
    working_dir: /teto
    volumes:
      - ./src:/teto/src
      - ./databases:/teto/databases
      - ./schemas:/teto/schemas
      - ./node_modules:/teto/node_modules
    networks:
      - back-tier
    environment:
      - BOT_ID=$BOT_ID
      - BOT_TOKEN=$BOT_TOKEN
      - BOT_PREFIX=$BOT_PREFIX
      - REDIS_URL=redis://127.0.0.1:6379
    depends_on:
      - redis
    command: node ./src/teto.js
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - back-tier
networks:
  back-tier: {}
