services:
  nodejs:
    image: node:15-alpine
    working_dir: /
    volumes:
      - ./src:/src
      - ./node_modules:/node_modules
    networks:
      - back-tier
    environment:
      - BOT_ID=$BOT_ID
      - BOT_TOKEN=$BOT_TOKEN
      - BOT_PREFIX=$BOT_PREFIX
      - REDIS_URL=redis://127.0.0.1:6379
    depends_on:
      redis:
        condition: service_started
    command: node ./src/teto.js
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - back-tier
networks:
  back-tier: {}
